
services:
  chevereto:
    image: ${image}
    container_name: 'chevereto'
    restart: ${restart}
    ports:
      - ${port}:80
    volumes: 
      - /etc/localtime:/etc/localtime
      - vol-chevereto:/config:rw
      - vol-chevereto:/var/www/html/images:rw
    # command: ["sleep", "10m"]         # 调试问题打开用
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Shanghai
    networks:
      net-custom:
        # ipv4_address: 172.19.254.199    # 指定 ip
        aliases: 
          - net-chevereto


networks: 
  net-custom:
    name: ${network}
    external: true 

    
volumes:
  vol-chevereto:
    external: true

